import React from "react"
import ReactDOM from "react-dom/client"

import App from "./App.tsx"
import "./styles.css"
import PettingZones from "./Components/Zone2.tsx"

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    {/* <img src="src/assets/Cute Cat Eating Fish.gif" useMap="#image-map"></img>

<map name="image-map">
    <area target="_blank" id = "Face" alt="Face" title="Face" onClick={() => console.log("BOOM! Face!")} coords="594,446,255" shape="circle"></area>
    <area target="_blank" alt="backFootLeft" title="backFootLeft" onClick={() => console.log("BOOM! foot 2!")} coords="785,933,932,1020" shape="rect"></area>
    <area target="_blank" alt="backFootRight" title="backFootRight" onClick={() => console.log("BOOM! Foot 1!")} coords="261,933,397,1018" shape="rect"></area>
    <area target="_blank" alt="foodBowl" title="foodBowl" onClick={() => console.log("BOOM! Food!")} coords="416,1079,442,981,453,952,472,942,495,934,505,929,513,905,540,896,566,899,591,908,602,922,632,923,665,930,694,935,723,947,736,961,747,975,753,988,756,1008,760,1029,764,1046,770,1069,772,1080,752,1094,672,1122,566,1127,450,1106,423,1093" shape="poly"></area>
    <area target="_blank" alt="mainBody" title="mainBody" onClick={() => console.log("BOOM! Body!")} coords="429,1017,405,1005,402,932,305,922,314,839,348,782,380,757,387,688,405,646,501,685,570,706,644,703,701,684,748,663,786,657,802,723,803,764,847,788,873,831,881,884,882,916,880,924,792,924,785,940,782,1002,763,1013,755,970,727,943,696,933,660,923,624,919,604,916,620,899,660,877,681,828,677,786,651,754,614,740,568,737,530,762,507,807,512,839,538,884,540,890,518,894,502,907,498,924,469,936,446,949" shape="poly"></area>
    <area target="_blank" alt="sensitiveBelly" title="sensitiveBelly" onClick={() => console.log("BOOM! Belly Time!")} coords="595,822,81" shape="circle"></area>
    <area target="_blank" alt="tailUp" title="tailUp" onClick={() => console.log("BOOM! Tail Up!")} coords="882,921,959,638" shape="rect"></area>
    <area target="_blank" alt="tailDown" title="tailDown" onClick={() => console.log("BOOM! Tail Down!")} coords="963,849,1074,976" shape="rect"></area>
    <area target="_blank" alt="outerHead" title="outerHead" onClick={() => console.log("BOOM! Ears, outer head!")} coords="402,640,372,705,273,642,252,567,236,523,267,378,217,214,233,133,448,55,567,164,663,173,756,81,808,69,1012,182,956,396,981,477,972,555,926,636,879,636,873,716,826,710,813,741,806,704,798,674,792,647,754,653,799,611,834,552,850,490,852,421,843,360,811,299,767,248,713,216,678,198,599,186,515,194,440,230,396,272,362,324,339,396,333,460,344,514,372,576,402,624" shape="poly"></area>
    <area target="_blank" alt="tailMid" title="tailMid" onClick={() => console.log("BOOM! Tail Mid!")} coords="966,764,1029,843,1070,841,1045,757,968,705" shape="poly"></area>
</map> */}

{/* <!-- Image Map Generated by http://www.image-map.net/ --> */}
<img src="src/assets/Cat using laptop.gif" useMap="#image-map"></img>
<PettingZones/>
{/* <map name="image-map">
    <area target="_blank" alt="Head" title="Head" onClick={() => console.log("onClick! Head!")} coords="120,238,111,186,128,144,127,63,183,90,233,80,277,91,329,63,340,84,335,146,348,187,344,223,330,252,297,273,255,283,211,287,178,279,158,240" shape="poly"></area>
    <area target="_blank" alt="DriverPaw" title="DriverPaw" onMouseDown={() => console.log("onmousedown! DriverPaw!")} coords="212,297,253,339" shape="rect"></area>
    <area target="_blank" alt="PassengerPaw" title="PassengerPaw" onMouseEnter={() => console.log("onmouseenter! PassPaw!")} coords="188,374,180,386,179,403,191,420,218,436,237,412,213,382" shape="poly"></area>
    <area target="_blank" alt="toeBeans" title="toeBeans" onTouchEnd={() => console.log("ontouchend! toebeans!")} coords="278,410,15" shape="circle"></area>
    <area target="_blank" alt="NonoZone" title="NonoZone" onTouchEnd={() => console.log("ontouchend! Belly!")} coords="248,374,16" shape="circle"></area>
    <area target="_blank" alt="CompRUS" title="CompRUS" onPointerLeave={() => console.log("onPointerLeave! Computer!")} coords="156,240,30,242,24,251,70,356,210,356,269,355,274,344,204,341" shape="poly"></area>
    <area target="_blank" alt="Body" title="Body" onPointerLeave={() => console.log("onPointerLeave! Body!")} coords="204,288,184,289,206,335,211,295,254,295,256,338,276,343,270,359,196,359,194,372,235,402,240,390,228,373,239,359,259,360,267,376,286,394,312,415,337,402,358,366,320,337,280,279" shape="poly"></area>
    <area target="_blank" alt="Back" title="Back" onPointerLeave={() => console.log("onPointerLeave! Back!")} coords="310,270,286,279,323,335,359,360,347,309" shape="poly"></area>
    <area target="_blank" alt="TailUp" title="TailUp" onTouchEnd={() => console.log("ontouchend! Tail!")} coords="339,289,323,274,331,256,354,242,385,232,418,265,420,307,404,323,389,337,372,349,357,355,358,327,370,287,371,275,364,260,355,265" shape="poly"></area>
    <area target="_blank" alt="tailDown" title="tailDown" onTouchStart={() => console.log("ontouchstart! TailDown!")} coords="361,358,361,370,394,368,411,364,436,348,472,337,459,306,441,292,426,287,409,296,362,332" shape="poly"></area>
    <area target="_blank" alt="DriverFoot" title="DriverFoot" onTouchEnd={() => console.log("ontouchend! driverFoot!")} coords="318,418,315,436,296,444,276,439,263,426,253,406,250,393,268,379,283,391,273,393,265,400,263,413,273,425,292,417,295,409,293,401" shape="poly"></area>
</map> */}
    <App />
  </React.StrictMode>
)
