import React from "react"
import ReactDOM from "react-dom/client"

import App from "./App.tsx"
import "./styles.css"
// import PettingZones from "./Components/HiCatPetMap.tsx"
// // import PettingZones from "./Components/Zone2.tsx"
// // import picture from "../src/assets/Cat using laptop.gif"
// import picture from "../src/assets/Cat Saying Hello.gif"

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
{/* <!-- Image Map Generated by http://www.image-map.net/ -->
<img src={picture} useMap="#image-map"></img>
<PettingZones/> */}

    <App />
  </React.StrictMode>
)
